### ISSUE TITLE
The virtual system "Spryker Dev VM v2.1.0 (build-268)" claims support for 8192 MB RAM size, but VirtualBox has support for min 4 & max 3584 MB RAM size only

### ISSUE THREAD

**Issue by ewallteam** [spryker-shop/b2b-demo-shop#7]
@spryker-bot 

Hi team, I have followed the instructions given in the below link **https://documentation.spryker.com/installation/installation-guide-b2b.htm#linux** to install the spryker b2b demo shop but I got the following error. Could anyone help me out.

```
VM_PROJECT=b2b-demo-shop SPRYKER_REPOSITORY="https://github.com/spryker-shop/b2b-demo-shop.git" vagrant up
Loading VM settings file: .vm
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'devvm2.1.0'...
Progress: 90%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/home/user/.vagrant.d/boxes/devvm2.1.0/0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "Spryker Dev VM v2.1.0 (build-268)_1546241645829_66191", "--vsys", "0", "--unit", "9", "--disk", "/home/user/VirtualBox VMs/Spryker Dev VM v2.1.0 (build-268)_1546241645829_66191/box-disk001.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/user/.vagrant.d/boxes/devvm2.1.0/0/virtualbox/box.ovf...
VBoxManage: warning: The virtual system "Spryker Dev VM v2.1.0 (build-268)" claims support for 8192 MB RAM size, but VirtualBox has support for min 4 & max 3584 MB RAM size only..
OK.
0%...10%...20%...30%...40%...50%...60%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the imported medium '/home/user/VirtualBox VMs/Spryker Dev VM v2.1.0 (build-268)_1546241645829_66191/box-disk001.vmdk'.
VBoxManage: error: VMDK: cannot write allocated data block in '/home/user/VirtualBox VMs/Spryker Dev VM v2.1.0 (build-268)_1546241645829_66191/box-disk001.vmdk' (VERR_DISK_FULL)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 886 of file VBoxManageAppliance.cpp
```

**Comment by sokyrko** [comment]
@ewallteam do you use 64 bit version of VirtualBox?

**Comment by ewallteam** [comment]
@spryker-bot
        I used the 32-bit version. Also kindly let me know the system requirement for RAM capacity.

Do you have any live demo for Spryker B2B?

**Comment by sokyrko** [comment]
Try to use 64bit VM please.

**Comment by ewallteam** [comment]
@sokyrko 

Sure I'll use 64bit VM.

Kindly let me know the RAM capacity for the VM.

**Comment by ewallteam** [comment]
@sokyrko 

Do you have any live demo for Spryker B2B?

**Comment by tvaleriy** [comment]
http://www.b2b.demo-spryker.com/

**Comment by tvaleriy** [comment]
And please use this info for access backend etc - https://now.spryker.com/login-b2c-demo-shop.

**Comment by ewallteam** [comment]
@tvaleriy

Thanks a lot!!!
Could you please share me the back-end and front-end login details.

**Comment by tvaleriy** [comment]
http://os.b2b.demo-spryker.com

admin@spryker.com
change123


Also existing customers have the same password, so you can either create your own customer, or find existing in the backoffice and login in the shop using the same password.

**Comment by ewallteam** [comment]
@tvaleriy 

Thanks for the information.

**Comment by ewallteam** [comment]
@tvaleriy 

Is that a limited period demo. As it is not working right now. Kindly confirm once.

**Comment by tvaleriy** [comment]
@ewallteam The instance should be up and running again.

**Comment by ewallteam** [comment]
@tvaleriy 

The site is working fine, thanks.
